Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,5 +39,11 @@ jobs:
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
           chmod 600 private_key
           scp -o StrictHostKeyChecking=no -i private_key -P 8822 deploy.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to copy deploy.sh to the server."
+            exit 1
+          fi
+          echo "deploy.sh successfully copied to the server."
+          
           ssh -o StrictHostKeyChecking=no -i private_key -p 8822 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash /tmp/deploy.sh'
           rm private_key
